### ISSUE TITLE
RSS Não passa pelo validador do W3C

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/search-books#49]
http://books.scielo.org/search/index.php?output=rss&site=livros&col=&lang=pt&sort=publication_date%2Bdesc

Validador do W3C: http://validator.w3.org/feed/

**Comment by amandasramalho** [comment]
@deandr @jamilatta 

No RSS, livros com "&" aparecem com o código "&amp;". Isto faz com que o plugin do Portal exiba o título com a informação "&amp;". Seria possível corrigir esta informação no RSS?
