### ISSUE TITLE
Alterar a analise dos termos da pesquisa (Query Parser).

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-books#53]
Esse ticket é motivado pelos problemas identificados nas pesquisa do SciELO periódicos.

Ver ticket: https://github.com/scieloorg/search-journals/issues/434

**Comment by jamilatta** [comment]
@amandasramalho

Solicitei para a equipe de infra a atualização do ambiente de produção com esse ajuste. 

A mudança visível é a de que título com dois pontos passam a ser retornados na pesquisa. 

Portanto nessa sequência de termos **'Atenção primária à saúde no Brasil: conceitos, práticas e pesquisa"** teríamos retornos satisfatórios no resultado de pesquisa

**Comment by amandasramalho** [comment]
@jamilatta 
Excelente. Quando for aplicado, me avise para validar.

**Comment by jamilatta** [comment]
@amandasramalho 

Sim estou aguardando a equipe de infra realizar a atualização!

**Comment by jamilatta** [comment]
@amandasramalho 

Poderia verificar esse ajuste no ambiente de produção. 
Eu juntamente com a infra acabamos de realizar esse ajuste.

**Comment by jamilatta** [comment]
@amandasramalho 

Caso esteja funcionando, podemos fechar esse ticket!

**Comment by amandasramalho** [comment]
@jamilatta 

Está funcionando! Testado com 3 títulos com dois pontos e recuperou corretamente.
